# Generated by Django 4.2.6 on 2023-11-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=340)),
                ('mainimage', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('description2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('minititle', models.CharField(blank=True, max_length=300, null=True)),
                ('title', models.CharField(max_length=1200)),
                ('description', models.TextField()),
                ('description2', models.TextField()),
                ('views', models.SmallIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=400)),
                ('contact', models.CharField(max_length=400)),
                ('email', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='HeaderSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minititle', models.CharField(max_length=330)),
                ('title', models.CharField(max_length=340)),
                ('mainimage', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=500)),
                ('icon', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='HomeAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_done', models.SmallIntegerField(blank=True, null=True)),
                ('happy_customer', models.SmallIntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=440)),
                ('description', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=600)),
                ('subject', models.CharField(max_length=500)),
                ('message', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('minititle', models.CharField(max_length=330)),
                ('title', models.CharField(max_length=340)),
                ('mainimage', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('description2', models.TextField()),
                ('icon', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('minititle', models.CharField(max_length=330)),
                ('title', models.CharField(max_length=340)),
                ('mainimage', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('description2', models.TextField()),
                ('icon', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
