# Generated by Django 4.2.6 on 2023-11-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='field',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
