# Generated by Django 4.2.6 on 2023-11-05 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_field_alter_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolia',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.field'),
        ),
    ]
