# Generated by Django 4.2.6 on 2023-11-06 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_services_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='message',
            name='subject',
        ),
    ]
